#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "lazylibrarian"
      intport: "5299"
      extport: "5299"
      image: "linuxserver/lazylibrarian"

# CORE (MANDATORY) ############################################################
  - name: CronJob Role
    include_tasks: "/opt/plexguide/containers/_core.yml"

# LABELS ######################################################################

  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.frontend.auth.basic.users: "{{auth.stdout}}"
        traefik.enable: "true"
        traefik.port: "{{intport}}"
  
        traefik.frontend.rule: "Host:lazy.{{domain.stdout}},{{pgrole}}.{{domain.stdout}},{{tldset}}"

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - "/opt/appdata/{{pgrole}}:/config"
        - "/mnt/unionfs/ebooks:/books"
        - "/mnt/unionfs/abooks:/abooks"
        - "{{path.stdout}}/torrentvpn/downloaded:/data/completed"
        - "{{path.stdout}}/sab/downloads:/config/Downloads"
        - "{{path.stdout}}/nzbget/completed:/completed"
        - "{{path.stdout}}/rutorrent:/downloads"
        - "{{path.stdout}}/deluge/downloaded:/downloaded"
        - "{{path.stdout}}/qbittorrent/downloads:/qbit-downloads"
        - "/etc/localtime:/etc/localtime:ro"

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000

# MAIN DEPLOYMENT #############################################################

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "{{pgrole}}"
      image: "{{image}}"
      pull: yes
      published_ports:
        - "{{ports.stdout}}{{extport}}:{{intport}}"
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: always
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      labels: "{{pg_labels}}"

# EXTRA FOR LAZY
  - name: Please Wait - Pending .conf generation from lazylibrarian
    wait_for:
      path: "/opt/appdata/lazylibrarian/config.ini"
      state: present

  - name: "Wait 5 Seconds"
    wait_for:
      timeout: 5

  - name: Set Incomplete Download Location
    lineinfile:
      path: "/opt/appdata/lazylibrarian/config.ini"
      regexp: 'audio_dir ='
      line: 'audio_dir = /abooks'
      state: present

  - name: Restart Container
    docker_container:
      name: lazylibrarian
      state: started
