#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "rtorrent"
      intport: "5000"
      extport: "5000"
      image: "robertbaker/rtorrent"

# CORE (MANDATORY) ############################################################
  - name: CronJob Role
    include_tasks: "/opt/plexguide/containers/_core.yml"

# LABELS ######################################################################

  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.frontend.auth.basic.users: "{{auth.stdout}}"
        traefik.enable: "true"
        traefik.port: "{{intport}}"

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - "{{path.stdout}}/{{pgrole}}:/downloads"
        - "/opt/appdata/{{pgrole}}/session:/session"
        - "/opt/appdata/{{pgrole}}/watch:/watch"
        - "/opt/appdata/{{pgrole}}/config:/config"
        - "/opt/appdata/{{pgrole}}/socket:/socket"
        - "/mnt/unionfs:/unionfs"
        - "{{path.stdout}}/{{pgrole}}:/data"
        - "/etc/localtime:/etc/localtime:ro"

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000
        RTORRENT_SOCK: true

# MAIN DEPLOYMENT #############################################################
  - name: RCCHECK
    stat:
      path: "/opt/appdata/{{pgrole}}/config/.rtorrent.rc"
    register: rccheck

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "{{pgrole}}"
      image: "{{image}}"
      pull: yes
      published_ports:
        - "{{ports.stdout}}{{extport}}:{{intport}}"
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: always
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      labels: "{{pg_labels}}"

  # ENDING TASK FOR RTORRENT ####################################################
  - name: "First Time Check"
    block:

    - name: rtorrent.rc creation
      wait_for:
        path: "/opt/appdata/{{pgrole}}/config/.rtorrent.rc"
        state: present
        msg: rtorrent.rc creation failed

    - name: "Stopping {{pgrole}}"
      docker_container:
        name: "{{pgrole}}"
        state: stopped

    - name: No File Allocation
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/.rtorrent.rc"
        regexp: 'system.file_allocate.set'
        line: 'system.file.allocate.set = 0'
        state: present

    - name: DL Location
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/.rtorrent.rc"
        regexp: 'directory.default.set'
        line: 'directory.default.set = /downloads/incoming'
        state: present

    - name: Restart Docker Container
      docker_container:
        name: "{{pgrole}}"
        state: started

    when: not rccheck.stat.exists
