#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "rutorrent"
      intport: "80"
      extport: "8999"
      image: "linuxserver/rutorrent"

# EXTRA FOR RUTORRENT #########################################################
  - name: "Create scripts folder - {{pgrole}}"
    file:
      path: /opt/appdata/{{pgrole}}/plugins
      state: directory
      owner: 1000
      group: 1000
      mode: 0755

  - name: "Copy scripts into directory - {{pgrole}}"
    copy:
      src: /opt/plexguide/containers/templates/{{pgrole}}/plugins
      dest: /opt/appdata/{{pgrole}}
      directory_mode: yes
      force: yes
      owner: 1000
      group: 1000
      mode: 0755

# CORE (MANDATORY) ############################################################
  - name: CronJob Role
    include_tasks: "/opt/plexguide/containers/_core.yml"

# LABELS ######################################################################

  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.frontend.auth.basic.users: "{{auth.stdout}}"
        traefik.enable: "true"
        traefik.port: "{{intport}}"
  
        traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - "/opt/appdata/{{pgrole}}/config:/config"
        - "/opt/appdata/{{pgrole}}:/scripts"
        - "/etc/localtime:/etc/localtime:ro"
        - "/mnt/unionfs:/unionfs"
        - "/mnt:/mnt"
        - "{{path.stdout}}/{{pgrole}}:/downloads"

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000

# MAIN DEPLOYMENT #############################################################
  - name: RCCHECK
    stat:
      path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
    register: rccheck

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "{{pgrole}}"
      image: "{{image}}"
      pull: yes
      published_ports:
        - "{{ports.stdout}}{{extport}}:{{intport}}"
        - "6881:6881/udp"
        - "51413:51413"
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: unless-stopped
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      purge_networks: yes
      stop_timeout: "240"
      labels: "{{pg_labels}}"

  # ENDING TASK FOR RUTORRENT ####################################################
  - name: "First Time Check"
    block:

    - name: rtorrent.rc creation
      wait_for:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        state: present
        msg: rtorrent.rc creation failed

    - name: "7 Second Hold"
      wait_for:
        timeout: 7

    - name: "Stopping {{pgrole}}"
      docker_container:
        name: "{{pgrole}}"
        state: stopped

    - name: Upload Rate
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        regexp: 'upload_rate'
        line: 'upload_rate = 100000'
        state: present

    - name: Download Rate
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        regexp: 'download_rate'
        line: 'download_rate = 100000'
        state: present

    - name: Low Disk - Set to 20GB
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        regexp: 'low_diskspace'
        line: 'schedule = low_diskspace,5,60,close_low_diskspace=20000M'
        state: present

    - name: Global Upload to Unlmited
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        regexp: 'throttle.global_up.max_rate.set_kb'
        line: 'throttle.global_up.max_rate.set_kb = 0'
        state: present

    - name: Set Encryption
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        regexp: 'encryption = allow_incoming,try_outgoing,enable_retry'
        line: 'encryption = allow_incoming,try_outgoing,enable_retry,prefer_plaintext'
        state: present

    - name: MAX DL 1024
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        regexp: 'throttle.global_down.max_rate.set_kb'
        line: 'throttle.max_downloads.global.set = 1024'
        state: present

    - name: No File Allocation
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        regexp: 'system.file_allocate.set'
        line: 'system.file.allocate.set = 0'
        state: present

    - name: DL Location
      lineinfile:
        path: "/opt/appdata/{{pgrole}}/config/rtorrent/rtorrent.rc"
        regexp: 'directory.default.set'
        line: 'directory.default.set = /downloads/incoming'
        state: present

    - name: Force New Plugin
      copy:
        src: /opt/plexguide/containers/templates/rutorrent.ini
        owner: 1000
        group: 1000
        dest: "/opt/appdata/{{pgrole}}/config/rutorrent/settings/plugins.ini"
        mode: 0775
        force: yes

    - name: Restart Docker Container
      docker_container:
        name: "{{pgrole}}"
        state: started

    when: not rccheck.stat.exists
