#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "sonarr"
      intport: "8989"
      extport: "8989"
      image: "linuxserver/sonarr"

# CORE (MANDATORY) ############################################################
  - name: CronJob Role
    include_tasks: "/opt/plexguide/containers/_core.yml"

# LABELS ######################################################################
  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.frontend.auth.basic.users: "{{auth.stdout}}"
        traefik.enable: "true"
        traefik.port: "{{intport}}"
  
        traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"

  - name: Create Folders
    file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
    with_items:
      - /opt/appdata/{{pgrole}}/mp4_automator

  - name: Install autoProcess.ini
    template:
      src: /opt/plexguide/containers/templates/sonarr.ini
      dest: /opt/appdata/{{pgrole}}/mp4_automator/autoProcess.ini
      force: yes
      mode: 0775
      owner: 1000
      group: 1000

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - "/opt/appdata/{{pgrole}}/mp4_automator:/config_mp4_automator"
        - "/opt/appdata/{{pgrole}}:/config"
        - "/mnt/unionfs:/unionfs"
        - "/mnt/:/mnt"
        - "{{path.stdout}}/sab/downloads:/config/Downloads"
        - "{{path.stdout}}/nzbget/downloads/completed:/completed"
        - "{{path.stdout}}/rutorrent:/downloads"
        - "{{path.stdout}}/deluge/downloaded:/downloaded"
        - "{{path.stdout}}/qbittorrent/downloads:/qbit-downloads"
        - "/etc/localtime:/etc/localtime:ro"

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000

# MAIN DEPLOYMENT #############################################################

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "{{pgrole}}"
      image: "{{image}}"
      pull: yes
      published_ports:
        - "{{ports.stdout}}{{extport}}:{{intport}}"
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: always
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      labels: "{{pg_labels}}"
