---
- name: Warning
  pause:
    prompt: "You are utilizing the STABLE image. If you prefer the BETA version, re-install later through the menu! Press Enter to Continue"

- name: Stop and remove any existing container
  docker_container:
    name: plex
    state: absent

- name: "Get Server IP"
  shell: "hostname -I | awk '{print $1}'"
  register: local_ip

- name: Check Preferences.xml exists
  stat:
    path: "/opt/appdata/plex/Library/Application Support/Plex Media Server/Preferences.xml"
  register: plex_prefs

- debug: msg="Your IP Address is {{local_ip.stdout}}"
  when: plex_prefs.stat.exists == False

- name: Get Plex Media Server claim token
  pause:
    prompt: "Visit http://plex.tv/claim, Copy to Clipboard, and Paste"
  register: pms_token
  when: plex_prefs.stat.exists == False

- debug: msg="Using following Plex claim token {{pms_token.user_input}}"
  when: plex_prefs.stat.exists == False

- name: Remove Plex Container
  docker_container:
    name: plex
    state: absent

- name: Pull Plex Image
  docker_image:
    name: "plexinc/pms-docker:plexpass"

- name: Deploy Plex Container
  docker_container:
    name: plex
    image: "plexinc/pms-docker:plexpass"
    pull: yes
    published_ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "33400:33400/tcp"
      - "33443:33443/tcp"
    env:
      PLEX_UID: 1000
      PLEX_GID: 1000
      CLAIM_TOKEN: "{{pms_token.user_input}}"
      ADVERTISE_IP: "http://{{local_ip.stdout}}:32400/"
#      ADVERTISE_IP: "http://{{ip4v}}:32400/"
      VIRTUAL_HOST: "plex.{{domain}}"
      VIRTUAL_PORT: 32400
      LETSENCRYPT_HOST: "plex.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
#    network_mode: "host"
    volumes:
      - "/tmp:/tmp"
      - "/opt/appdata/plex/database:/config"
      - "/opt/appdata/plex/transcode:/transcode"
      - "/mnt/plexdrive4:/plexdrive4"
      - "/mnt/encrypt:/encrypt"
      - "/mnt/unionfs:/unionfs"
      - "/:/yourcomputer"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: plexguide
        aliases:
          - plex
    cpu_shares: 1024
    restart_policy: always
    state: started
