---
- hosts: localhost
  vars_files:
    - /opt/appdata/plexguide/var.yml

### ensure to delete traefik from portainer or add the following to nginx main.yml
#- name: Remove Traefik
#  docker_container:
#    name: traefik
#    state: absent
## comment out vars_files parts
## sudo ansible-playbook /opt/plexguide/ansible/plexguide2.yml --tags var
## then comment back in vars_files parts and comment out var role
## ensure to update plexguide
## sudo ansible-playbook /opt/plexguide/ansible/config.yml <<< to generate the var file required above
## sudo ansible-playbook /opt/plexguide/ansible/plexguide2.yml --tags var
## sudo ansible-playbook /opt/plexguide/ansible/plexguide2.yml --tags docker
## sudo ansible-playbook /opt/plexguide/ansible/plexguide2.yml --tags nginx
## sudo ansible-playbook /opt/plexguide/ansible/plexguide2.yml --tags sonarrssl

  roles:
  - { role: nginx, tags: ['nginx'] }
  - { role: docker, tags: ['docker'] }
  - { role: radarrssl, tags: ['radarrssl'] }
  - { role: sonarrssl, tags: ['sonarrssl'] }
  - { role: var, tags: ['var'] }
  - { role: wordpress, tags: ['wordpress'] }
  - { role: netdatassl, tags: ['netdatassl'] }
  - { role: plexssl, tags: ['plexssl'] }
  - { role: embyssl, tags: ['embyssl'] }
  - { role: portainerssl, tags: ['portainerssl'] }
  - { role: nzbgetssl, tags: ['nzbgetssl'] }
  - { role: ombissl, tags: ['ombissl'] }
